// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_2H4TTnfg8Br8T-fpDZcz9KKChJqNc08',
    appId: '1:984590794939:web:82dfd72f45ec31720d299e',
    messagingSenderId: '984590794939',
    projectId: 'deliveryapp-c1a5f',
    authDomain: 'deliveryapp-c1a5f.firebaseapp.com',
    storageBucket: 'deliveryapp-c1a5f.firebasestorage.app',
    measurementId: 'G-RPS5DHL4ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_KTvVwW8K-Xa2R96nhsYIjIHF8UAmZ4M',
    appId: '1:984590794939:android:ddcb8bec7e898ead0d299e',
    messagingSenderId: '984590794939',
    projectId: 'deliveryapp-c1a5f',
    storageBucket: 'deliveryapp-c1a5f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_2H4TTnfg8Br8T-fpDZcz9KKChJqNc08',
    appId: '1:984590794939:web:5206d17da3f97d0c0d299e',
    messagingSenderId: '984590794939',
    projectId: 'deliveryapp-c1a5f',
    authDomain: 'deliveryapp-c1a5f.firebaseapp.com',
    storageBucket: 'deliveryapp-c1a5f.firebasestorage.app',
    measurementId: 'G-MLNGH37Y8Q',
  );
}
